### ISSUE TITLE
Is it possible to support Azure OpenAI?

### ISSUE THREAD

**Issue by Stark-X** [psychic-api/doctran#5]

**Comment by clemlesne** [comment]
`deployment_id` and `model` parameters are required for OpenAI SDK to talk to OpenAI instances on Azure.

The error I have is:

```
exception=InvalidRequestError(message="Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>", param='engine', code=None, http_status=None, request_id=None)>
```

Integration examples:

```python
openai.Embedding.create(
  deployment_id="xxx",
  input=prompt,
  model="xxx",
)

completion = openai.ChatCompletion.create(
  deployment_id="xxx",
  messages=messages,
  model="xxx",
)
```

Proposed integration:

```python
ChatOpenAI(
  model_name="xxx",
  deployment_id="xxx",
  model="xxx",
)
```

**Comment by EliasGitHub** [comment]
I'm getting the same error @clemlesne . Is there any workaround to let us using Doctran with Azure OpenAI deployments like "gpt-35-turbo"? appreciate any help!!

**Comment by maciejwie** [comment]
I've created a PR to add Azure OpenAI support: #11

**Comment by timxieICN** [comment]
Do we have someone reviewing @maciejwie 's PR above?

**Comment by Ayan-Bandyopadhyay** [comment]
Merged just now

**Comment by yb-sid** [comment]
I'm still facing error after installing doctran via `pip install doctran`:

TypeError: __init__() got an unexpected keyword argument 'openai_deployment_id'
